branch-defaults:
  master:
    environment: replens-dev
    group_suffix: null
global:
  application_name: replens-dev
  branch: null
  default_ec2_keyname: replens
  default_platform: PHP 7.2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
